# Generated by Django 2.2.7 on 2019-11-09 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
