# Generated by Django 2.2.7 on 2019-11-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_invites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invites',
            name='details',
        ),
        migrations.RemoveField(
            model_name='invites',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='invites',
            name='position',
        ),
        migrations.RemoveField(
            model_name='invites',
            name='startdate',
        ),
    ]
