# Generated by Django 2.2.7 on 2019-11-09 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20191109_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='role',
        ),
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auth.Role'),
        ),
    ]
